t_list  *ft_create_elem(void *data);
t_list  *ft_list_last(t_list *begin_list);
t_list  *ft_list_push_strs(int size, char **strs);
t_list  *ft_list_at(t_list *begin_list, unsigned int nbr);
t_list  *ft_list_find(t_list *begin_list, void *data_ref, int (*cmp)(void *, void *));
void    ft_list_push_front(t_list **begin_list, void *data);
void    ft_list_push_back(t_list **begin_list, void *data);
void    ft_list_clear(t_list *begin_list, void (*free_fct)(void *));
void    ft_list_reverse(t_list **begin_list);
void    ft_list_foreach(t_list *begin_list, void (*f)(void *));
void    ft_list_foreach_if(t_list *begin_list, void (*f)(void *), void *data_ref, int (*cmp)(void *, void *));
void    ft_list_remove_if(t_list **begin_list, void *data_ref, int (*cmp)(void *, void *), void (*free_fct)(void *));
void    ft_list_merge(t_list **begin_list1, t_list *begin_list2);
void    ft_list_sort(t_list **begin_list, int (*cmp)(void *, void *));
void    ft_list_reverse_fun(t_list *begin_list);
